iaas-configurations:
- additional_cloud_properties: {}
  availability_mode: ((availability_mode))
  bosh_storage_account_name: ((pks-bosh-storage-account))
  client_id: ((azure-client-id))
  client_secret: ((azure-client-secret))
  cloud_storage_type: managed_disks
  deployed_cloud_storage_type: managed_disks
  environment: AzureCloud
  name: default
  resource_group_name: ((pks-resource-group))
  ssh_private_key: ((pks-opsman-ssh-key.private_key))
  ssh_public_key: ((pks-opsman-ssh-key.public_key))
  storage_account_type: Premium_LRS
  subscription_id: ((azure-subscription-id))
  tenant_id: ((azure-tenant-id))
network-assignment:
  network:
    name: infrastructure
  other_availability_zones: []
  singleton_availability_zone:
    name: zone-1
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: ((pks-network-resource-group))/((pks-opsman-vnet))/pcf-infra
      cidr: ((pks-vnet-infra-cidr))
      dns: ((pks-vnet-dns))
      gateway: ((pks-vnet-infra-gateway))
      reserved_ip_ranges: ((pks-vnet-infra-reserved))
      availability_zone_names:
      - zone-1
      - zone-2
      - zone-3
  - name: management
    subnets:
    - iaas_identifier: ((pks-network-resource-group))/((pks-opsman-vnet))/pks-management
      cidr: ((pks-vnet-management-cidr))
      dns: ((pks-vnet-dns))
      gateway: ((pks-vnet-management-gateway))
      reserved_ip_ranges: ((pks-vnet-management-reserved))
      availability_zone_names:
      - zone-1
      - zone-2
      - zone-3
  - name: pcf-services
    subnets:
    - iaas_identifier: ((pks-network-resource-group))/((pks-opsman-vnet))/pcf-services
      cidr: ((pks-vnet-services-cidr))
      dns: ((pks-vnet-dns))
      gateway: ((pks-vnet-services-gateway))
      reserved_ip_ranges: ((pks-vnet-services-reserved))
      availability_zone_names:
      - zone-1
      - zone-2
      - zone-3
properties-configuration:
  director_configuration:
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: time.google.com
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: false
    skip_director_drain: false
  dns_configuration:
    excluded_recursors: []
    handlers: []
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: false
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
vmextensions-configuration: []
