
---
opsman-configuration:
  azure:
    subscription_id: ((azure-subscription-id))
    tenant_id: ((azure-tenant-id))
    client_id: ((azure-client-id))
    client_secret: ((azure-client-secret))
    resource_group: ((pks-resource-group))
    location: ((pks-opsman-location))
    container: opsmanagerimage
    network_security_group: ((pks-opsman-security-group))
    vpc_subnet: /subscriptions/((azure-subscription-id))/resourceGroups/((pks-network-resource-group))/providers/Microsoft.Network/virtualNetworks/((pks-opsman-vnet))/subnets/((pks-opsman-subnet))
    storage_account: ((pks-opsman-storage-account))
    ssh_public_key: ((pks-opsman-ssh-key.public_key))
    vm_name: ((pks-opsman-vm-name))
    private_ip: ((pks-opsman-private-ip))