product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: ((pks-api-cert.certificate))
      private_key_pem: ((pks-api-cert.private_key))
  .properties.cloud_provider:
    selected_option: azure
    value: Azure
  .properties.cloud_provider.azure.azure_cloud_name:
    value: AzurePublicCloud
  .properties.cloud_provider.azure.azure_master_managed_identity:
    value: pks-master
  .properties.cloud_provider.azure.azure_worker_managed_identity:
    value: pks-worker
  .properties.cloud_provider.azure.default_security_group:
    value: ((pks-api-security-group))
  .properties.cloud_provider.azure.location:
    value: ((pks-opsman-location))
  .properties.cloud_provider.azure.primary_availability_set:
    value: ((pks-vm-availability-set))
  .properties.cloud_provider.azure.resource_group_name:
    value: ((pks-resource-group))
  .properties.cloud_provider.azure.subscription_id:
    value: ((azure-subscription-id))
  .properties.cloud_provider.azure.tenant_id:
    value: ((azure-tenant-id))
  .properties.cloud_provider.azure.vnet_name:
    value: ((pks-opsman-vnet))
  .properties.cloud_provider.azure.vnet_resource_group_name:
    value: ((pks-network-resource-group))
  .properties.log_sink_resources_deploy:
    value: true
  .properties.metric_sink_resources_deploy:
    value: true
  .properties.network_selector:
    selected_option: flannel
    value: flannel
  .properties.network_selector.flannel.pod_network_cidr:
    value: 10.200.0.0/16
  .properties.network_selector.flannel.service_cluster_cidr:
    value: 10.100.200.0/24
  .properties.pks-vrli:
    selected_option: disabled
    value: disabled
  .properties.pks-vrops:
    selected_option: disabled
    value: disabled
  .properties.pks_api_hostname:
    value: ((pks-api-hostname))
  .properties.plan1_selector:
    selected_option: active
    value: Plan Active
  .properties.plan1_selector.active.allow_privileged_containers:
    value: false
  .properties.plan1_selector.active.description:
    value: 'Example: This plan will configure a lightweight kubernetes cluster. Not
      recommended for production workloads.'
  .properties.plan1_selector.active.master_az_placement:
    value:
    - zone-1
    - zone-2
    - zone-3
  .properties.plan1_selector.active.master_instances:
    value: 1
  .properties.plan1_selector.active.max_worker_instances:
    value: 50
  .properties.plan1_selector.active.name:
    value: small
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - zone-1
    - zone-2
    - zone-3
  .properties.plan1_selector.active.worker_instances:
    value: 3
  .properties.plan2_selector:
    selected_option: active
    value: Plan Active
  .properties.plan2_selector.active.allow_privileged_containers:
    value: false
  .properties.plan2_selector.active.description:
    value: 'Example: This plan will configure a medium sized kubernetes cluster, suitable
      for more pods.'
  .properties.plan2_selector.active.master_az_placement:
    value:
    - zone-1
    - zone-2
    - zone-3
  .properties.plan2_selector.active.master_instances:
    value: 3
  .properties.plan2_selector.active.max_worker_instances:
    value: 50
  .properties.plan2_selector.active.name:
    value: medium
  .properties.plan2_selector.active.worker_az_placement:
    value:
    - zone-1
    - zone-2
    - zone-3
  .properties.plan2_selector.active.worker_instances:
    value: 5
  .properties.plan3_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan4_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan5_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan6_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan7_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan8_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan9_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan10_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.proxy_selector:
    selected_option: disabled
    value: Disabled
  .properties.syslog_selector:
    selected_option: disabled
    value: disabled
  .properties.telemetry_selector:
    selected_option: disabled
    value: disabled
  .properties.uaa:
    selected_option: internal
    value: internal
  .properties.uaa_oidc:
    value: false
  .properties.uaa_pks_cli_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: 21600
  .properties.wavefront:
    selected_option: disabled
    value: disabled
  .properties.worker_max_in_flight:
    value: 1
network-properties:
  network:
    name: management
  other_availability_zones:
  - name: zone-1
  - name: zone-2
  - name: zone-3
  service_network:
    name: ((pks-api-service-network))
  singleton_availability_zone:
    name: zone-1
resource-config:
  pivotal-container-service:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
    elb_names:
    - ((pks-api-lb-name))
errand-config:
  delete-all-clusters:
    pre-delete-state: true
  pks-nsx-t-precheck:
    post-deploy-state: false
  smoke-tests:
    post-deploy-state: false
  upgrade-all-service-instances:
    post-deploy-state: true
  wavefront-alert-creation:
    post-deploy-state: false
  wavefront-alert-deletion:
    pre-delete-state: false

